<a href="https://colab.research.google.com/github/Kenmax15/AI-Language-Teaching-Assistant/blob/main/AI_Cancer_Diagnosis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [5]:
data = pd.read_csv("/cancer.csv")

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis(1=m, 0=b)      569 non-null    int64  
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [7]:
data.shape

(569, 31)

In [8]:
data.head()

diagnosis(1=m, 0=b)  radius_mean  texture_mean  perimeter_mean  area_mean  \
0                    1        17.99         10.38          122.80     1001.0   
1                    1        20.57         17.77          132.90     1326.0   
2                    1        19.69         21.25          130.00     1203.0   
3                    1        11.42         20.38           77.58      386.1   
4                    1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [9]:
data.columns

Index(['diagnosis(1=m, 0=b)', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [10]:
data.loc[0,"radius_mean"]

17.99

In [11]:
data.loc[1,"area_mean"]

1326.0

In [12]:
data.iloc[0,0]

1

In [13]:
data.dtypes

diagnosis(1=m, 0=b)          int64
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
dtype: object

In [14]:
data.isnull().sum()

diagnosis(1=m, 0=b)        0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [15]:
data["diagnosis(1=m, 0=b)"].unique()

array([1, 0])

In [16]:
#@title Setting X and y

In [17]:
X = data.drop(columns="diagnosis(1=m, 0=b)")

In [18]:
y = data["diagnosis(1=m, 0=b)"]

In [19]:
X.shape

(569, 30)

In [20]:
y.unique()

array([1, 0])

In [ ]:
#@title Splitting data

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [1]:
#@title Model

In [22]:
model = tf.keras.models.Sequential()

In [24]:
model.add(tf.keras.layers.Dense(256, input_shape=(X_train.shape[1],), activation="sigmoid"))
model.add(tf.keras.layers.Dense(256, activation="sigmoid"))
model.add(tf.keras.layers.Dense(1, activation="sigmoid"))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [27]:
#@title Compilation

In [25]:
model.compile(optimizer="adam", loss="crossentropy", metrics=["accuracy"])

In [ ]:
#@title fit the model

In [28]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.5901 - loss: 0.6409
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8832 - loss: 0.4355 
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9208 - loss: 0.2767 
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8925 - loss: 0.2667 
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9275 - loss: 0.2124 
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8961 - loss: 0.2577 
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8945 - loss: 0.2700 
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8953 - loss: 0.2607 
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8899 - loss: 0.2888 
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9237 - loss: 0.2265
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9146 - loss: 0.2441
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - a

In [ ]:
#@title Evaluate the model

In [31]:
model.evaluate(X_test, y_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9616 - loss: 0.1378  


[0.15130892395973206, 0.9561403393745422]

In [ ]:
#@title Predict

In [56]:
X.columns[0]

'radius_mean'

In [80]:
x_new = {'radius_mean':23, 'texture_mean':18.6, 'perimeter_mean':101.15, 'area_mean':10,
       'smoothness_mean':0.0058, 'compactness_mean':0.56, 'concavity_mean':0.3,
       'concave points_mean':0.04, 'symmetry_mean':0.1598, 'fractal_dimension_mean':0.0094,
       'radius_se':0.867, 'texture_se':2.05, 'perimeter_se':1.984, 'area_se':100, 'smoothness_se':0.0008,
       'compactness_se':0.07654, 'concavity_se':0.465, 'concave points_se':0.36, 'symmetry_se':0.067,
       'fractal_dimension_se':0.78, 'radius_worst':2.06, 'texture_worst':40.87,
       'perimeter_worst':90.106, 'area_worst':2023, 'smoothness_worst':0.23,
       'compactness_worst':1.676, 'concavity_worst':0.2769, 'concave points_worst':0.3962,
       'symmetry_worst':0.597, 'fractal_dimension_worst':1.0}

In [81]:
for key in X.columns:
  x_new[key] = [x_new[key]]

In [82]:
x_new

{'radius_mean': [23],
 'texture_mean': [18.6],
 'perimeter_mean': [101.15],
 'area_mean': [10],
 'smoothness_mean': [0.0058],
 'compactness_mean': [0.56],
 'concavity_mean': [0.3],
 'concave points_mean': [0.04],
 'symmetry_mean': [0.1598],
 'fractal_dimension_mean': [0.0094],
 'radius_se': [0.867],
 'texture_se': [2.05],
 'perimeter_se': [1.984],
 'area_se': [100],
 'smoothness_se': [0.0008],
 'compactness_se': [0.07654],
 'concavity_se': [0.465],
 'concave points_se': [0.36],
 'symmetry_se': [0.067],
 'fractal_dimension_se': [0.78],
 'radius_worst': [2.06],
 'texture_worst': [40.87],
 'perimeter_worst': [90.106],
 'area_worst': [2023],
 'smoothness_worst': [0.23],
 'compactness_worst': [1.676],
 'concavity_worst': [0.2769],
 'concave points_worst': [0.3962],
 'symmetry_worst': [0.597],
 'fractal_dimension_worst': [1.0]}

In [83]:
X_new = pd.DataFrame(x_new)

In [84]:
model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


array([[0.9993238]], dtype=float32)