<a href="https://colab.research.google.com/github/Kenmax15/AI-Language-Teaching-Assistant/blob/main/Deep_Learning_03_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

print(torch.__version__)
print(torch.cuda.is_available)

2.3.1+cu121
<function is_available at 0x7fd82015fd00>


In [3]:
first_tensor = torch.tensor([1,2,3,4,5,6], dtype=torch.int8)

In [4]:
first_tensor.device

device(type='cpu')

In [5]:
first_tensor.dtype

torch.int64

In [31]:
second_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(second_tensor[2])
print(second_tensor[2][1])
print(second_tensor[2][1].item())

tensor([7, 8, 9])
tensor(8)
8


In [7]:
first_tensor.shape

torch.Size([6])

In [8]:
second_tensor.shape

torch.Size([3, 3])

In [9]:
first_tensor.ndim

1

In [10]:
second_tensor.ndim

2

In [11]:
third_tensor = torch.tensor([1,2,3,4,5,6], dtype=torch.int8)

In [12]:
third_tensor.dtype

torch.int8

In [14]:
fifth_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float32)
fifth_tensor.dtype

torch.float32

In [15]:
sixth_tensor = fifth_tensor.int()
sixth_tensor.dtype

torch.int32

In [17]:
last_tensor = sixth_tensor.to(dtype=torch.float32)
last_tensor.dtype

torch.float32

In [19]:
#@title torch.rand() selects random values from a uniform distribution on the interval [0-1]
torch.manual_seed(111)
torch.rand(4,4)

tensor([[0.7156, 0.9140, 0.2819, 0.2581],
        [0.6311, 0.6001, 0.9312, 0.2153],
        [0.6033, 0.7328, 0.1857, 0.5101],
        [0.7545, 0.2884, 0.5775, 0.0358]])

In [20]:
#@title torch.randint() selects random integers generated uniformly between specified low and high values
torch.randint(-1, 10, (4,4), dtype=torch.int8)

tensor([[3, 9, 5, 0],
        [5, 2, 0, 9],
        [4, 1, 0, 1],
        [5, 3, 1, 6]], dtype=torch.int8)

In [21]:
torch.full_like(second_tensor,8)

tensor([[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]])

In [25]:
start_tensor = torch.rand(4,4)

In [26]:
torch.rand_like(start_tensor)

tensor([[0.7821, 0.0133, 0.3243, 0.9077],
        [0.8574, 0.1983, 0.0267, 0.9153],
        [0.2590, 0.2468, 0.9635, 0.7522],
        [0.2083, 0.1104, 0.6183, 0.8033]])

In [35]:
torch.manual_seed(111)
my_tensor = torch.rand(4,5)
print(my_tensor)

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
        [0.6001, 0.9312, 0.2153, 0.6033, 0.7328],
        [0.1857, 0.5101, 0.7545, 0.2884, 0.5775],
        [0.0358, 0.1026, 0.3419, 0.4400, 0.6341]])


In [36]:
my_tensor[0, 1:]

tensor([0.9140, 0.2819, 0.2581, 0.6311])

In [41]:
my_tensor[2, 1:3]

tensor([0.5101, 0.7545])

In [45]:
my_tensor[2, :]

tensor([0.1857, 0.5101, 0.7545, 0.2884, 0.5775])

In [44]:
my_tensor[2, :2]

tensor([0.1857, 0.5101])

In [43]:
my_tensor[2, ::2]

tensor([0.1857, 0.7545, 0.5775])

In [39]:
#@title Use indexing to extract data that meets some criteria
my_tensor[my_tensor<0.5]

tensor([0.2819, 0.2581, 0.2153, 0.1857, 0.2884, 0.0358, 0.1026, 0.3419, 0.4400])

In [47]:
#@title Combining tensors
torch.stack((my_tensor, my_tensor))

tensor([[[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
         [0.6001, 0.9312, 0.2153, 0.6033, 0.7328],
         [0.1857, 0.5101, 0.7545, 0.2884, 0.5775],
         [0.0358, 0.1026, 0.3419, 0.4400, 0.6341]],

        [[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
         [0.6001, 0.9312, 0.2153, 0.6033, 0.7328],
         [0.1857, 0.5101, 0.7545, 0.2884, 0.5775],
         [0.0358, 0.1026, 0.3419, 0.4400, 0.6341]]])

In [11]:
#@title Math functions
a = torch.rand((4,4), dtype=torch.float32)
b = torch.rand((4,4), dtype=torch.float32)

# Addition
print(a.add(b))

# Substraction
print(a.sub(b))

#multiplication
print(a.mul(b))

# Division
print(a.div(b))

tensor([[0.8011, 1.0141, 0.8624, 0.6769],
        [0.7749, 1.2094, 1.0069, 1.0054],
        [0.7862, 1.7927, 1.0773, 0.3044],
        [0.1552, 0.6439, 1.4607, 1.3835]])
tensor([[ 0.2785, -0.8882,  0.0130,  0.5404],
        [ 0.2546,  0.7537,  0.4354,  0.9370],
        [ 0.6598,  0.1521, -0.6438, -0.2462],
        [ 0.1185,  0.0854, -0.0170,  0.0292]])
tensor([[0.1411, 0.0599, 0.1859, 0.0415],
        [0.1339, 0.2236, 0.2061, 0.0332],
        [0.0457, 0.7977, 0.1865, 0.0080],
        [0.0025, 0.1018, 0.5333, 0.4783]])
tensor([[ 2.0659,  0.0662,  1.0306,  8.9182],
        [ 1.9788,  4.3081,  2.5237, 28.4169],
        [11.4430,  1.1854,  0.2519,  0.1058],
        [ 7.4510,  1.3058,  0.9770,  1.0431]])


In [18]:
#@title Reduction function
# mean
print(torch.mean(a).item())

# median
print(torch.median(a).item())

# mode
print(torch.mode(a))

# standard deviatio
print(torch.std(a).item())

0.5442968606948853
0.5398398041725159
torch.return_types.mode(
values=tensor([0.0630, 0.5147, 0.0291, 0.1368]),
indices=tensor([1, 0, 3, 0]))
0.31588566303253174


In [19]:
#@title Linear Algebra Operations

# tensor multiplication
torch.matmul(a,b)

tensor([[0.1963, 1.0568, 1.0736, 0.5716],
        [0.4532, 1.5760, 1.8372, 0.9249],
        [0.4561, 1.0952, 0.7930, 0.1620],
        [0.1892, 1.0026, 1.3054, 0.6988]])

In [21]:
a1 = torch.randn(2, 3)
a2 = torch.randn(3, 4)
a3 = torch.randn(4, 5)
a4 = torch.randn(5, 6)
a5 = torch.randn(6, 7)

torch.linalg.multi_dot((a1, a2, a3, a4, a5))

tensor([[  5.4122,  -1.0021,  -2.0708,  -1.2507,   8.6064,   1.0929,  -2.6536],
        [  6.9316,  -7.8718, -31.2475,  13.4878,   6.6283, -12.1659, -13.7253]])

In [9]:
#@title Computing eigenspectrum

A = torch.randn(16384, 16384)
#print("Matrix", A)

eigenvalues = torch.linalg.eig(A)

print("Eigen Values:", eigenvalues)
#print("Eigen Vectors:", eigenvectors)

Eigen Values: torch.return_types.linalg_eig(
eigenvalues=tensor([-98.1215+83.1832j, -98.1215-83.1832j, -82.5499+98.7296j,
         ...,   0.7386-0.5669j,   1.2054+0.0000j,
         -2.1668+0.0000j]),
eigenvectors=tensor([[ 0.0018+0.0064j,  0.0018-0.0064j,  0.0002+0.0038j,  ...,
         -0.0036+0.0105j,  0.0127+0.0000j, -0.0064+0.0000j],
        [-0.0123-0.0025j, -0.0123+0.0025j,  0.0040-0.0044j,  ...,
         -0.0037+0.0032j,  0.0080+0.0000j, -0.0010+0.0000j],
        [-0.0024+0.0047j, -0.0024-0.0047j,  0.0070+0.0015j,  ...,
          0.0069-0.0024j, -0.0038+0.0000j, -0.0068+0.0000j],
        ...,
        [ 0.0083-0.0056j,  0.0083+0.0056j, -0.0017-0.0019j,  ...,
         -0.0034+0.0014j, -0.0028+0.0000j,  0.0122+0.0000j],
        [ 0.0009+0.0105j,  0.0009-0.0105j,  0.0019+0.0052j,  ...,
          0.0029-0.0070j,  0.0036+0.0000j, -0.0057+0.0000j],
        [-0.0092+0.0009j, -0.0092-0.0009j, -0.0030+0.0002j,  ...,
          0.0046-0.0015j, -0.0059+0.0000j,  0.0014+0.0000j]]))


In [11]:
#@title Automatic differentiation
x = torch.autograd.Variable(torch.Tensor([2]), requires_grad=True)
y = torch.autograd.Variable(torch.Tensor([1]), requires_grad=True)
z = torch.autograd.Variable(torch.Tensor([5]), requires_grad=True)

In [15]:
a = x - y
f = z * a

print("Final value for function f = ", f)

f.backward()

print("Gradient Value for x:", x.grad)
print("Gradient Value for y:", y.grad)
print("Gradient Value for z:", z.grad)

Final value for function f =  tensor([5.], grad_fn=<MulBackward0>)
Gradient Value for x: tensor([20.])
Gradient Value for y: tensor([-20.])
Gradient Value for z: tensor([4.])


In [19]:
#@title Splitting tensors

x = torch.randn(8, 5)
y = torch.rand(1, 16)

In [22]:
x

tensor([[-1.6380,  0.1258,  1.0994,  0.6038, -0.3840],
        [ 0.3304,  0.9646,  1.6871,  1.5041,  1.2922],
        [ 0.8475, -0.8630,  0.5309,  0.3987,  0.5416],
        [-2.1047, -0.4401, -1.5042, -0.6420,  1.2588],
        [-0.8649,  1.7420,  1.2662, -0.0789,  0.0984],
        [-0.7474, -0.0160, -0.4318,  1.6326, -0.1828],
        [ 0.6725,  0.7540,  0.6394,  0.0337, -0.7533],
        [-2.5792,  0.6701,  0.2400, -1.3310,  0.4652]])

In [20]:
y

tensor([[0.9754, 0.9950, 0.6671, 0.5647, 0.8825, 0.2698, 0.3151, 0.9197, 0.4397,
         0.6903, 0.6568, 0.9500, 0.7575, 0.2978, 0.3616, 0.5534]])

In [23]:
x.size(0)

8

In [29]:
torch.split(x, 4, dim=0)

(tensor([[-1.6380,  0.1258,  1.0994,  0.6038, -0.3840],
         [ 0.3304,  0.9646,  1.6871,  1.5041,  1.2922],
         [ 0.8475, -0.8630,  0.5309,  0.3987,  0.5416],
         [-2.1047, -0.4401, -1.5042, -0.6420,  1.2588]]),
 tensor([[-0.8649,  1.7420,  1.2662, -0.0789,  0.0984],
         [-0.7474, -0.0160, -0.4318,  1.6326, -0.1828],
         [ 0.6725,  0.7540,  0.6394,  0.0337, -0.7533],
         [-2.5792,  0.6701,  0.2400, -1.3310,  0.4652]]))

In [27]:
torch.chunk(x, 4, dim=0)

(tensor([[-1.6380,  0.1258,  1.0994,  0.6038, -0.3840],
         [ 0.3304,  0.9646,  1.6871,  1.5041,  1.2922]]),
 tensor([[ 0.8475, -0.8630,  0.5309,  0.3987,  0.5416],
         [-2.1047, -0.4401, -1.5042, -0.6420,  1.2588]]),
 tensor([[-0.8649,  1.7420,  1.2662, -0.0789,  0.0984],
         [-0.7474, -0.0160, -0.4318,  1.6326, -0.1828]]),
 tensor([[ 0.6725,  0.7540,  0.6394,  0.0337, -0.7533],
         [-2.5792,  0.6701,  0.2400, -1.3310,  0.4652]]))

In [30]:
torch.split(x, [5,3], dim=0)

(tensor([[-1.6380,  0.1258,  1.0994,  0.6038, -0.3840],
         [ 0.3304,  0.9646,  1.6871,  1.5041,  1.2922],
         [ 0.8475, -0.8630,  0.5309,  0.3987,  0.5416],
         [-2.1047, -0.4401, -1.5042, -0.6420,  1.2588],
         [-0.8649,  1.7420,  1.2662, -0.0789,  0.0984]]),
 tensor([[-0.7474, -0.0160, -0.4318,  1.6326, -0.1828],
         [ 0.6725,  0.7540,  0.6394,  0.0337, -0.7533],
         [-2.5792,  0.6701,  0.2400, -1.3310,  0.4652]]))

In [32]:
torch.split(y, [4,6,6], dim=1)

(tensor([[0.9754, 0.9950, 0.6671, 0.5647]]),
 tensor([[0.8825, 0.2698, 0.3151, 0.9197, 0.4397, 0.6903]]),
 tensor([[0.6568, 0.9500, 0.7575, 0.2978, 0.3616, 0.5534]]))